#Integracion Continua
language: node_js
node_js: 14.17.1
git: 
  depth: 3
addons:
  sonarcloud: 
    organization: 'leanA23'
    token: "c2e1325e06b6183d98497ca191458717ad2b45c7"
script:
  - yarn test
  - sonar-scanner
notifications: 
  email:
    recipients:
      - reloco23@gmail.com
    on_success: always
    on_failure: always
#Despliegue Continuo
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 7adff61d-fb85-4ac3-8775-52a1bcbbbc04
  app: tp-is
  on:
    repo: LeanA23/TP-IS