#Integracion Continua
language: node_js
node_js: 14.17.1
git: 
  depth: 3
branches:
  only: 
  - main
addons:
  sonarcloud: 
    organization: "lean23"
    token: "874845056fde0f16d684cb4283fe123b0c9b0835"

script:
  - yarn test
  - sonar-scanner

notifications: 
  slack: isutn2021:2w5NbVWR4c1qrqQ31AJI6G82

#Despliegue Continuo
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 7adff61d-fb85-4ac3-8775-52a1bcbbbc04
  app: tp-is
  on:
    repo: LeanA23/TP-IS
    branch: main